# netlify.toml
[build]
  command = "echo 'No build command needed for static site with functions'"
  publish = "." # Указывает, что корень репозитория является папкой для публикации

[functions]
  directory = "netlify/functions" # Папка, где будут храниться ваши функции

# Перенаправление для всех запросов на корневой путь "/"
# Это правило означает, что функция `ip-redirect` будет обрабатывать все запросы к корневому пути.
[[redirects]]
  from = "/"
  to = "/.netlify/functions/ip-redirect" # Путь к вашей функции
  status = 200 # Важно: 200, чтобы функция могла решить, что отдавать (не перенаправлять сразу)
  force = true # Принудительно используем эту функцию
